In [22]:
from sklearn import svm
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC,SVR
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

In [5]:
#df = pd.read_csv("your_data.csv")
#X = df.drop('target_column_name', axis=1)
#y = df['target_column_name']

In [6]:
iris=datasets.load_iris()
x=iris.data
y=iris.target

In [16]:
#standarlize
std = StandardScaler()
x_std = std.fit_transform(x)
#
x_train, x_test, y_train, y_test = train_test_split(x_std, y, test_size=0.3, stratify=y, random_state=1)

In [17]:
#modeling linear, rbf, poly
svm_classification = SVC(kernel='rbf', C=1.0, gamma='auto', random_state=42)
svm_classification.fit(x_train, y_train)
svm_classification.score(x_test, y_test)

0.9777777777777777

In [18]:
y_pred = svm_classification.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9777777777777777
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.94      1.00      0.97        15
           2       1.00      0.93      0.97        15

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [21]:
svm_classification.support_vectors_
svm_classification.support_
svm_classification.n_support_

array([ 9, 18, 18], dtype=int32)

In [27]:
from sklearn.model_selection import GridSearchCV
params={
    'kernel':('linear','rbf','poly'),
    'C':[0.1, 0.5, 1, 10]}
model = GridSearchCV(estimator=svm_classification, param_grid=params, cv=5)
model.fit(x_train, y_train)
print("best model", model.best_params_)
print("best score", model.best_score_)

best model {'C': 0.1, 'kernel': 'linear'}
best score 0.9523809523809523


In [32]:
print(svm_classification.predict([[1, 1, 7, 2]]))


[1]


In [38]:
clfovo = SVC(decision_function_shape='ovo')
clfovo.fit(x_train, y_train)
clfovo.decision_function([[1,2,2,9]])

array([[-0.01658993, -0.10776607,  0.03225873]])

In [37]:
clfovr=SVC(decision_function_shape='ovr')
clfovr.fit(x_train, y_train)
clfovr.decision_function([[1,2,2,9]])

array([[-0.03686733,  2.01552454,  1.02340208]])

In [ ]:
clf = svm.OneClassSVM(nu=0.05, kernel="rbf", gamma=0.1)
clf.fit(X_train)